5a = int(input(' Digite um numero pra ver sua Tabuada '))
print('_'*15)
print('{} x 1 = {:2}'.format(a, (a*1)))
print('{} x 2 = {:2}'.format(a, (a*2)))
print('{} x 3 = {:2}'.format(a, (a*3)))
print('{} x 4 = {:2}'.format(a, (a*4)))
print('{} x 5 = {:2}'.format(a, (a*5)))
print('{} x 6 = {:2}'.format(a, (a*6)))
print('{} x 7 = {:2}'.format(a, (a*7)))
print('{} x 8 = {:2}'.format(a, (a*8)))
print('{} x 9 = {:2}'.format(a, (a*9)))
print('{} x 10 = {:2}'.format(a, (a*10)))
print('_'*15)
